openapi: 3.0.0
info:
  title: Cloudmesh AI Analytics  Services
  description: Cloudmesh Scikit-Learn AI Analytics Services
  license:
    name: Apache 2.0
  version: 0.0.2

servers:
  - url: http://localhost:8000/cloudmesh-ai-services

paths:
  /file/upload:
    post:
      summary: uploading file to the server
      operationId: cloudmesh.file.upload
      requestBody:
        description: the file uploaded by the user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: upload succeed
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    file_name:
                      type: string
        default:
          description: incompatible file format
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    error_message:
                      type: string
  /file/list:
    get:
      summary: list all uploaded files
      operationId: cloudmesh.file.list
      responses:
        '200':
          description: upload succeed
        default:
          description: incompatible file format
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    error_message:
                      type: string

  /file/read/{file_name}:
    get:
      summary: read file content
      operationId: cloudmesh.file.read
      parameters:
        - in: path
          name: file_name   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The file name to be read
      responses:
        '200':
          description: succeed
        default:
          description: incompatible file format
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    error_message:
                      type: string

  /analytics/linear-regression/{file_name}:
    post:
      summary: doing linear regression
      operationId: cloudmesh.analytics.linear_regression
      parameters:
        - in: path
          name: file_name   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file_name:
                  type: string
                fit_intercept:
                  type: boolean
                normalize:
                  type: boolean
                n_jobs:
                  type: integer
      responses:
        '200':
          description: cpu info


  /analytics/pca:
    get:
      summary: principle components analysis
      operationId: cloudmesh.analytics.pca # working directory
      responses:
        '200':
          description: cpu info
