openapi: 3.0.0
info:
  title: ai services
  description: ai services included in scikit-learn
  license:
    name: Apache 2.0
  version: 0.0.1

servers:
  - url: http://localhost:8000/cloudmesh-ai-services

paths:
  /upload:
    post:
      summary: uploading file to the server
      operationId: ai_service.ai_services.upload
      requestBody:
        description: the file uploaded by the user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: upload succeed
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    file_name:
                      type: string
        default:
          description: incompatible file format
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    error_message:
                      type: string
  /list-files:
    get:
      summary: list all uploaded files
      operationId: ai_service.ai_services.list_files
      responses:
        '200':
          description: upload succeed
        default:
          description: incompatible file format
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    error_message:
                      type: string

  /read-file/{file_name}:
    get:
      summary: read file content
      operationId: ai_service.ai_services.read_file
      parameters:
        - in: path
          name: file_name   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The file name to be read
      responses:
        '200':
          description: succeed
        default:
          description: incompatible file format
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    error_message:
                      type: string

  /linear-regression/{file_name}:
    post:
      summary: doing linear regression
      operationId: ai_service.ai_services.run_linear_regression
      parameters:
        - in: path
          name: file_name   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: cpu info


  /pca:
    get:
      summary: principle components analysis
      operationId: ai_service.ai_services.run_pca # working directory
      responses:
        '200':
          description: cpu info